spring:
  application:
    name: sboard
  datasource:
    url: jdbc:mariadb://localhost:3316/testdb
    username: boardmgr
    password: boardmgr
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      indielab: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.indielab.demo.sboard.model
  mapper-locations: classpath:mapper/**/*.xml
