spring:
  application:
    name: sboard
  datasource:
    url: jdbc:mariadb://localhost:3316/testdb
    username: boardmgr
    password: boardmgr
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE